// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5K3MI5htYromSB1M4AjCSWaD7YL4fk4',
    appId: '1:417992603605:web:c0aad930003882f4f96f5c',
    messagingSenderId: '417992603605',
    projectId: 'fastscore-b82f4',
    authDomain: 'fastscore-b82f4.firebaseapp.com',
    storageBucket: "fastscore-b82f4.firebasestorage.app",
    measurementId: 'G-8YSKG9NE4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLXAtBhGpcfCshdnW5HNg2XkeOdsxVU4',
    appId: '1:417992603605:android:f136f6e5656a9ea7f96f5c',
    messagingSenderId: '417992603605',
    projectId: 'fastscore-b82f4',
    storageBucket: 'fastscore-b82f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9y8rCGourRCJr7hTHLIliwT0GlZh3REc',
    appId: '1:417992603605:ios:f6b689a35954831bf96f5c',
    messagingSenderId: '417992603605',
    projectId: 'fastscore-b82f4',
    storageBucket: 'fastscore-b82f4.firebasestorage.app',
    iosBundleId: 'com.example.fastscoreFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9y8rCGourRCJr7hTHLIliwT0GlZh3REc',
    appId: '1:417992603605:ios:f6b689a35954831bf96f5c',
    messagingSenderId: '417992603605',
    projectId: 'fastscore-b82f4',
    storageBucket: 'fastscore-b82f4.firebasestorage.app',
    iosBundleId: 'com.example.fastscoreFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ5K3MI5htYromSB1M4AjCSWaD7YL4fk4',
    appId: '1:417992603605:web:cc59be9925a1da2cf96f5c',
    messagingSenderId: '417992603605',
    projectId: 'fastscore-b82f4',
    authDomain: 'fastscore-b82f4.firebaseapp.com',
    storageBucket: 'fastscore-b82f4.firebasestorage.app',
    measurementId: 'G-YXJC85R7JQ',
  );
}
